name: Upload assets to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload assets to release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: PharmGKB/PharmCAT.wiki
          path: 'PharmCAT.wiki'

      - name: Set appVersion
        uses: bhowell2/github-substring-action@v1
        id: appVersion
        with:
          value: ${{github.ref}}
          index_of_str: "refs/tags/v"

      - run: echo "Version = ${{steps.appVersion.outputs.substring}}"

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Package app
        run: ./gradlew shadowJar

      - name: Package preprocessor
        run: make scriptPkg

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: build/libs/pharmcat-${{steps.appVersion.outputs.substring}}-all.jar
          overwrite: true

      - name: Upload preprocessor to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: build/preprocessor.tar.gz
          asset_name: pharmcat-preprocessor-${{steps.appVersion.outputs.substring}}.tar.gz
          overwrite: true

      - name: Upload positions.vcf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf
          overwrite: true

      - name: Upload positions.vcf.bgz to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf.bgz
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf.bgz
          overwrite: true

      - name: Upload positions.vcf.bgz.tbi to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf.bgz.tbi
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf.bgz.tbi
          overwrite: true

      - name: Send Slack notification on failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dev
          status: FAILED
          color: danger

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
